### ISSUE TITLE
dat-browserify is not equivalent with hyperdrive + hyperdiscovery

### ISSUE THREAD

**Issue by aschrijver** [karissa/dat-browserify#3]
Hi @karissa 

I updated the link in your readme, but they are pointing to other node-based non-browserified core modules of the dat ecosystem.
Should it point elsewhere, or is it better adding a notice that you decided not to complete the project?

I ask because I was looking into shimming dat packages for use with react native, and bumped into this project.

**Comment by karissa** [comment]
I think this repo should be deleted in favor of dat-js -- but dat-js may need package.json updated for the newest hyperdrive

**Comment by aschrijver** [comment]
Does dat-js work? Browserify does not include `fs` I thought. Especially for the sync stuff I figured some code needs modifying in e.g. hypercore-protocol to make it work with RN and in browser.

**Comment by karissa** [comment]
There is a sync module for webrtc (present currently in the dat-js code) and hyperdrive has an in-memory storage that we'd use instead of the `fs` based storage

**Comment by aschrijver** [comment]
so you use a modified dat-protocol package? Or did you shim the fs.readFileSync that is there?

**Comment by karissa** [comment]
You use `random-access-memory`. This is built into hyperdrive. 

We need to update the docs on this! 

Here's an example in the hyperdrive tests: https://github.com/mafintosh/hyperdrive/blob/master/test/helpers/create.js#L1

**Comment by aschrijver** [comment]
Yes, I know about the r-a-m, but I was referring to calls like these: https://github.com/mafintosh/hypercore-protocol/blob/master/messages.js#L5 and potentially many other similar calls throughout the dependency tree which have no equivalent on async android devices and must be shimmed.

**Comment by karissa** [comment]
Hey @aschrijver, I updated the code for hyperdrive 9 here, so you can see it: https://github.com/datproject/dat-js/pull/7

`fs` calls work fine with browserify. The problem I'm running into now is not having replication work. Going to close this in favor of the above PR. Thanks for your time!

**Comment by aschrijver** [comment]
Thanks @karissa for that link!

Strange.. browserify-fs is based on level-filesystem, which has no readFileSync.

https://github.com/mafintosh/level-filesystem/blob/master/README.md

**Comment by mk-pmb** [comment]
For files that are available on transform time, [`brfs`](https://github.com/substack/brfs) might be used to shim some simple cases of `fs.readFileSync`. Dunno whether there's any support for the more complicated cases, or for sync read at runtime.

**Comment by aschrijver** [comment]
:thumbsup: once more :)
